### ISSUE TITLE
PFM image with not-a-one scale is not displayed properly.

### ISSUE THREAD

**Issue by Kri-Ol** [kopaka1822/ImageViewer#18]
**Describe the bug**

If I generate grey-scale PFM with third parameter being different from 1, image in the viewer won't change

e.g.

Pf
100 100
-1.0
.....

will be displayed the same as 

Pf
100 100
-5.0
.....

**To Reproduce**
Make simple PFM grey-scale with scale = 1. Display it. Change scale from -1 to -5. Same display

**Expected behavior**
Display should behave same was as if I multiplied data array by 5.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Version: 3.4

**Additional context**

**Comment by kopaka1822** [comment]
Hello, I fixed this in the last commit. Can you built the new binary yourself or do you want me to supply one for you?

**Comment by Kri-Ol** [comment]
Would appreciate official build, thank you

**Comment by kopaka1822** [comment]
Hey, I drafted a new release: https://github.com/kopaka1822/ImageViewer/releases
Your fix should be included, please check it out
