### ISSUE TITLE
3.5 download zip is tagged with a virus

### ISSUE THREAD

**Issue by hypnosnhendricks** [kopaka1822/ImageViewer#20]
**Describe the bug**
When trying to download the 3.5 version of the ZIP, Windows/Chrome won't allow it to be downloaded, saying it contains a virus.

**To Reproduce**
1. Go to https://github.com/kopaka1822/ImageViewer
2. Click on https://github.com/kopaka1822/ImageViewer/raw/Release/Build/ImageViewer3_5.zip
3. See error

**Expected behavior**
3.5 downloads correctly and virus free.

**Screenshots**
![image](https://user-images.githubusercontent.com/43652836/128915555-8a1275d4-f0d6-437e-9610-e21e8a5f97c2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**

**Comment by kopaka1822** [comment]
Hello,
I don't know what went wrong with this release, but after rebuilding the project it is no longer detected as a virus (at least for me).
Please check out the download link again.

The only thing that should pop up now is this:
![image](https://user-images.githubusercontent.com/19892238/129001888-db46888b-b233-45aa-bcdc-0bba02aa7462.png)
Where you can just go on __More Info__ and then __Run anyway__
