### ISSUE TITLE
Add shortcut to turn off/on alpha channel and shortcut to show Alpha channel only.

### ISSUE THREAD

**Issue by powof2** [kopaka1822/ImageViewer#22]
**Is your feature request related to a problem? Please describe.**
its not related to any problem.
Add shortcut to see texture in RGB mode (turn off Alpha channel)
Add shortcut to see texture in Alpha only mode (trun off RGB channel)

**Describe the solution you'd like**
just like XnView
press 'M', xnview will display alpha channel only ('M' means Mask, i guess)
press 'M' again, xnview ill restored to its previous display mode.
press Ctrl + 'H', turn off textures alpha channel.

**Comment by kopaka1822** [comment]
Hello,
for now you can use the image equations to achieve this behaviour:
> see texture in RGB mode (turn off Alpha channel)

On the right side of the editor, click on the chains next to the alpha channel to enable editing. Then set A to 1 and click apply:
![Capture](https://user-images.githubusercontent.com/19892238/142405624-ecb04686-1f68-4ee5-aacd-52c8eeb94a79.PNG)

> see texture in Alpha only mode (trun off RGB channel)

Choose Alpha(I0) for RGB and 1 for A. Again, click apply:
![grafik](https://user-images.githubusercontent.com/19892238/142405882-b31ce7bf-363e-4475-a167-853146ecd3c0.png)

You can also click on the question mark next to the image equation, or navigate to Help->Equation to get a better explanation on how this works: https://github.com/kopaka1822/ImageViewer/blob/master/Docs/equation.md

I am not sure if I want to add shortcuts for this yet.

**Comment by powof2** [comment]
It works great!
I think it is enough for now, no need for short cut.
Thank you.
