### ISSUE TITLE
Hope to support horizontal or vertical CUbeMap conversion of latitude and longitude

### ISSUE THREAD

**Issue by sunkai174634** [kopaka1822/ImageViewer#25]
**Describe the solution you'd like**
Hope to support horizontal or vertical CUbeMap conversion of latitude and longitude

**Additional context**
![image](https://user-images.githubusercontent.com/22735821/175917568-8d6c0dc9-61ec-41a5-ada8-84ae861d1e63.png)

**Comment by kopaka1822** [comment]
Hello,
I am not completely sure which feature you want.
Do you have a latitude longitude image and want to convert it to a cubemap?
Or do you have have the 6 pictures and want to convert them to a latitute longitude image?
