### ISSUE TITLE
malware included? im unsure...

### ISSUE THREAD

**Issue by B-eT-a** [kopaka1822/ImageViewer#26]
hey there, just did a weekly scan of my System and it really didnt like the imageViewer.exe.
what gives? 

https://www.virustotal.com/gui/file/e60dfd191999eeaec4f1201cdb0e03ec1a89a21eb009c335043fc8b4a758f77d

new scan - above was older - but still same result :(
https://www.virustotal.com/gui/file/e60dfd191999eeaec4f1201cdb0e03ec1a89a21eb009c335043fc8b4a758f77d?nocache=1

**Comment by kopaka1822** [comment]
I dont know how these scanners judge things. I just know that I need update the json library, which i will do with the next release
