### ISSUE TITLE
ImageConsole.exe using float as a filterparam

### ISSUE THREAD

**Issue by clanfreak1988** [kopaka1822/ImageViewer#27]
**Describe the bug**
When you try to use a filter parameter with a dot number, the tool will try to convert in to a int.

**To Reproduce**
.\ImageConsole.exe -open .\\\<ktx file>  -addfilter .\Filter\gamma.hlsl -filterparam 0 Gamma 0.5 -export .\\\<pngfilename>.png RGBA8_SRGB

**Expected behavior**
I expected thats i can use float as a filter param

**Screenshots**
Error message:
could not convert "0.5" at index 2 to integer

**Desktop (please complete the following information):**
Windows 10

**Additional context**
The problem is in the file FilterParameterCommand.cs in the line 31. You try to read in as int not as a float. I fix it locally and test it.
Problemcode block
```
case ParameterType.Float:
  fp.GetFloatModel().Value = reader.ReadInt("value");
  break;
```
Fixedcode Block
```
case ParameterType.Float:
  fp.GetFloatModel().Value = reader.ReadFloat("value");
  break;
```

**Comment by kopaka1822** [comment]
Thank you for your contribution. I fixed it in the latest commit
