### ISSUE TITLE
Lock alpha equation

### ISSUE THREAD

**Issue by Jojendersie** [kopaka1822/ImageViewer#5]
Minor priority improvement.

Use a lock symbol to make the alpha equation match the RGB equation. Default is locked. Only allow typing in the alpha equation if the lock is explicitly released.
I have observed people to always edit both equations -- even if there is no alpha channel. And even if there is an alpha channel the wanted default behaviour is likely a copy.

**Comment by kopaka1822** [comment]
This might be a bad idea for difference equations like (I0-I1)^2.
The alpha would result in 0 and nothing would be visible.
