### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by tebriz159** [kopaka1822/ImageViewer#7]
Hello mate, I want to contribute on your project. I made a logo for imageviewer. Here's the logo if you want to use it I can send PR or all files to use it.

![imageviewer](https://user-images.githubusercontent.com/31902754/47182981-c2a40500-d2db-11e8-8b78-03248e1ddd63.png)

**Comment by kopaka1822** [comment]
Thank you for your effort but I prefer the current logo
